### ISSUE TITLE
Bidet en lavet ontbreken in de referentiedata

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#104]
In het beleidshandboek van de huurcomissie voor het woningwaardeeringstelsel wordt voor zowel een bidet als een lavet één punt toegekend. In de huidige referentiedata ontbreken deze twee type`bouwkundigelementdetailsoort`

<img width="737" alt="image" src="https://github.com/Aedes-datastandaarden/vera-referentiedata/assets/10978711/155e832d-f992-465a-8c64-0e5ff9e08388">

**Comment by sTomerG** [comment]
Hoe dit kan worden toegevoegd aan de referentiedata:

```csv
BOUWKUNDIGELEMENTDETAILSOORT;BID;Bidet;Billenbadje. Een laag bekken voor het wassen van het zitvlak, te gebruiken na bijvoorbeeld de stoelgang, zowel te gebruiken met warm als met koud water.;;;BOUWKUNDIGELEMENTSOORT.VOO;Vastgoed
BOUWKUNDIGELEMENTDETAILSOORT;LAV;Lavet;Een combinatie van een klein zitbad, een grote diepe gootsteenbak en een op heuphoogte aangebrachte, zeer diepe douchebak;;;BOUWKUNDIGELEMENTSOORT.VOO;Vastgoed
```

**Comment by RomyMans** [comment]
In de ILS groep besproken: in de volgende versie van de Aedes ILS worden bidet en lavet toegevoegd.

@peterjan-aedesdatastandaarden is het gelukt dit te verwerken?
