### ISSUE TITLE
Onduidelijkheid omtrent gemeenschappelijke dakterras varianten

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#108]
Er zijn momenteel twee typen gemeenschappelijk dakterras in de referentiedata;

- `gemeenschappelijk_dakterras_gak` met als parent `Buitenruimte` en beschrijving: _Buitenruimte: een gemeenschappelijk dakterras_
- `gemeenschappelijk_dakterras_gda` met als parent `Gemeenschappelijke ruimten en voorzieningen` zonder beschrijving. 

Wat is het verschil hiertussen? 

Bij tuin is er bijvoorbeeld maar één gemeenschappelijke variant: `gemeenschappelijke_tuin` met als parent `Gemeenschappelijke ruimten en voorzieningen`. 

Het zou top zijn als hier meer duidelijkheid over kan worden gegeven!

**Comment by benataedes** [comment]
Beste Tomer,

De Ruimtedetailsoort GDA is obsolete; deze moet daarom niet meer gebruikt worden. Gebruik in plaats daarvan de Ruimtedetailsoort GAK.

Groet,
Ben Bouwland
VERA-Architectuurteam

**Comment by benverhees** [comment]
@benataedes wellicht is het goed om die regel dan van een einddatum te voorzien, zodat dit duidelijker is?

**Comment by sTomerG** [comment]
@benataedes vanwaar is een gemeenschappelijk dakterras een `buitenruimte` en een gemeenschappelijke tuin een `gemeenschappelijke ruimten en voorzieningen`?

**Comment by sTomerG** [comment]
Aangezien dit issue al gesloten is heb ik een nieuw issue aangemaakt m.b.t. tot `buitenruimte` als parent vs `gemeenschappelijke_ruimten_en_voorzieningen`: #118
