### ISSUE TITLE
Meeteenheid millimeter mist in referentiedata

### ISSUE THREAD

**Issue by tiddoloos** [Aedes-datastandaarden/vera-referentiedata#115]
In vera is de lengte van een bouwkundigelement (BouwkundigElementenBouwkundigElement.lengte) gemodelleerd in millimeter. Alleen mist de meeteenheid millimeter in de referentiedata. Zou millimeter misschien toegevoegd kunnen worden aan de referentiedata Meeteenheid?

**Comment by MarcelVanDenBos** [comment]
Zojuist toegevoegd
