### ISSUE TITLE
schuur heeft als parent buitenruimte i.p.v. overige ruimte

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#116]
in de referentiedata is de parent van een `schuur` een `buitenruimte`, maar in het beleidsboek valt een schuur onder `overige ruimtes`

<img width="899" alt="image" src="https://github.com/Aedes-datastandaarden/vera-referentiedata/assets/10978711/069ff258-4fef-41a6-8768-e721e309f681">

**Comment by RomyMans** [comment]
@EwoutAtAedes besproken met de ILS groep en Tomer. Lijkt ons goed dit te corrigeren zolang we hiervan gebruik maken.

**Comment by RomyMans** [comment]
Hierbij dan verzoek of dit gecorrigeerd kan worden @MarcelVanDenBos :) als daar twijfel over bestaat hoor ik het graag en dan neem ik het mee terug naar de ILS groep

**Comment by MarcelVanDenBos** [comment]
Aangepast.
