### ISSUE TITLE
'ruimtes' en 'ruimten' worden door elkaar gebruikt

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#117]
In de referentiedata worden de woorden 'ruimtes' en 'ruimten' door elkaar gebruikt; bijvoorbeeld:

`ruimtesoort` telt:

`Overige ruimtes`
en 
`Gemeenschappelijke ruimten en voorzieningen`

Wellicht dat het voor consistentie en duidelijkheid het fijner is om één van de twee te kiezen voor de referentiedata en die overal toe te passen i.p.v. één keer de één en één keer de ander?

**Comment by sTomerG** [comment]
Aanvullend hierop:

`ruimtesoort`: `Overige ruimtes` en `Gemeenschappelijke ruimten en voorzieningen` is meervoudig, maar ruimtesoort `vertrek` is enkelvoudig

Wellicht kan consistentie hierin ook gelijk worden meegenomen :)

**Comment by MarcelVanDenBos** [comment]
We hebben van ruimtes ruimten gemaakt. m.b.t. Overige ruimtes geeft aan dat het er verschillende kunnen zijn. Vertrek is eenduidig en daarom enkelvoudig.

**Comment by sTomerG** [comment]
> We hebben van ruimtes ruimten gemaakt. m.b.t. Overige ruimtes geeft aan dat het er verschillende kunnen zijn. Vertrek is eenduidig en daarom enkelvoudig.

Dank voor de update m.b.t. consistentie in het schrijven van ruimten/ruimtes :).

Waar ik nog benieuwd naar ben, waarom is `vertrek` eenduidig?

Een `woonkamer`, `badkamer`, `slaapkamer` vallen allen onder `vertrek`, net zoals dat een `berging`, `gang` en `toiletruimte` onder `overige ruimten` vallen. Waarom is het één eenduidiger dan het ander?
