### ISSUE TITLE
Laadpaal ontbreekt in referentiedata

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#125]
Met de nieuwe woningwet die per 1 juli ingaat is maximaal 2 punten te verdienen met een laadpaal, maar op dit moment is `laadpaal` alleen een `PRIJSCOMPONENTDETAILSOORT`, maar wellicht zou het moeten worden toegevoegd als `BOUWKUNDIGELEMENTDETAILSOORT`?

![image](https://github.com/Aedes-datastandaarden/vera-referentiedata/assets/10978711/0bf8334c-73af-4a6f-944b-59ac786b8bc8)

**Comment by MarcelVanDenBos** [comment]
We voegen Laadpaal toe als bouwkundigelementdetailsoort in VERA. Aedes-ILS voegt het toe als object.
We leggen een relatie tussen ruimte en bouwkundige elementen.

**Comment by MarcelVanDenBos** [comment]
De Industry Foundation Classes (IFC) code voor een laadpaal (elektrische laadpaal voor voertuigen) is doorgaans gerelateerd aan de classificatie voor elektrische componenten en infrastructuur. In het IFC-schema wordt een laadpaal vaak geclassificeerd onder "IfcElectricAppliance" of een vergelijkbare entiteit.

De specifieke classificatie kan variëren afhankelijk van de gedetailleerde modellering en het gebruikte BIM-softwareplatform. Hieronder zijn enkele mogelijkheden:

IfcElectricAppliance: Dit is een algemene classificatie voor elektrische apparaten. Een laadpaal kan hieronder vallen als het wordt gemodelleerd als een elektrisch apparaat.

PredefinedType: In sommige gevallen kan een specifieke waarde voor "PredefinedType" worden gebruikt om de laadpaal verder te specificeren.
IfcFlowTerminal: In sommige gevallen wordt een laadpaal gemodelleerd als een terminal waar elektrische energie wordt geleverd aan voertuigen.

PredefinedType: Hier kan ook een specifieke waarde worden gebruikt om de functie van de laadpaal te specificeren.
IfcEnergyConversionDevice: In gevallen waarin de laadpaal wordt gezien als een apparaat dat energie omzet of levert, kan deze classificatie worden gebruikt.

PredefinedType: Bijvoorbeeld "CHARGER" of een vergelijkbare specifieke typeaanduiding.

**Comment by RomyMans** [comment]
In de ILS 3.0 is laadpaal toegevoegd als objecttype.
