### ISSUE TITLE
Referentiedata COMMUNICATIEVOORKEURSOORT ontbreekt

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-referentiedata#130]
**Probleem**
Zie: https://www.coraveraonline.nl/index.php/Klasse:BRG-Relaties-Communicatievoorkeur/VERA_4.1_Patches

Hierna wordt verwezen naar de referentiedata COMMUNICATIEVOORKEURSOORT. Deze bestaat alleen niet.

**Oplossing**
Graag de ontbrekende referentiesoort toevoegen, of verwijzen naar een andere referentiesoort.

**Comment by peterjan-aedesdatastandaarden** [comment]
We hebben COMMUNICATIEVOORKEURSOORT toegevoegd aan de referentiedata.
