### ISSUE TITLE
Eengezinswoning en Meergezinswoning/Duplexwoning niet te herleiden vanuit `EenhedenEenheid`

### ISSUE THREAD

**Issue by tiddoloos** [Aedes-datastandaarden/vera-referentiedata#131]
Vanuit de referentiedata `Eenheiddetailsoort` mist een referentie naar "Eengezinswoning" en "Meergezinswoning/Duplexwoning". Momenteel is alleen vanuit de comments te herleiden welke `Eenheiddetailsoort` tot de "Eengezinswoningen" en "Meergezinswoningen/Duplexwoningen" behoren. Of een eenheid tot "Eengezinswoning" of "Meergezinswoninge/Duplexwoning" behoort is bijvoorbeeld van belang bij het waarderen van de Energieprestatie in het woningwaarderingstelsel. Is het mogelijk om "Eengezinswoning" en "Meergezinswoning/Duplexwoning" op een manier aan `EenhedenEenheid` toe te voegen zodat het een werkbare referentie wordt?

**Comment by MarcelVanDenBos** [comment]
@benataedes zie dat de Referentiedata nog niet beschikbaar is.

**Comment by benataedes** [comment]
Referentiedata PANDSOORT is een tijd geleden al toegevoegd.
