### ISSUE TITLE
Keuken en sanitaire voorzieningen in referentiedata

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#132]
De woningwaardering voor zelfstandige woonruimten die is ingegaan per 1 juli 2024 bevat de volgende keuken- en sanitaire voorzieningen waarvoor punten kunnen worden gegeven. 

In de referentiedata ontbreken veel van deze voorzieningen (ovens, magnetron, kookplaten). Deze zouden wij vraag toegevoegd zien. Is dit iets voor de ILS-werkgroep of kunnen wij zelf een opzet doen?

Indien het gaat om een object in een bepaalde ruimte (zoals ‘toilet in een aparte ruimte' of ‘toilet in een badkamer’) is de definite van een object 'toilet’ genoeg, aangezien die aan een ruimte kan worden meegegeven. 

#### Keukenvoorzieningen

[Zie 5.4](https://arc.net/l/quote/unhyppap)

| Voorziening                              |
|------------------------------------------|
| Inbouw afzuiginstallatie*                |
| Inbouw kookplaat inductie                |
| Inbouw kookplaat keramisch               |
| Inbouw kookplaat gas                     |
| Inbouw koelkast                          |
| Inbouw vrieskast                         |
| Inbouw oven elektrisch                   |
| Inbouw oven gas                          |
| Inbouw magnetron                         |
| Inbouw vaatwasmachine                    |
| Extra kastruimte boven het minimum (per 60 cm breedte, met een minimum van 60 cm hoogte) |
| Éénhandsmengkraan                        |
| Thermostatische mengkraan                |
| Kokend waterfunctie (al dan niet apart of in aanvulling op de kraan) |

[Zie 6.1](https://arc.net/l/quote/eezcpjiz)

#### Sanitaire voorzieningen

| Voorziening                              |
|------------------------------------------|
| Toilet in een aparte ruimte              |
| Toilet in een badkamer                   |
| Hangend toilet in aparte ruimte          |
| Hangend toilet in badkamer               |
| Wastafel*                                |
| Meerpersoonswastafel                     |
| Douche                                   |
| Bad                                      |
| Bad en douche                            |

#### Aanvullende sanitaire voorzieningen

[Zie 6.2](https://arc.net/l/quote/wkxgoyai)

| Voorziening                              |
|------------------------------------------|
| Bubbelfunctie van het bad                |
| Gemonteerde volledige afscheiding van de douche* |
| Handdoekenradiator                       |
| Ingebouwd kastje met in- of opgebouwde wastafel |
| Kastruimte (minimale breedte van 40cm, en minimale hoogte van 40cm) |
| Stopcontact (maximaal twee per wastafel) |
| Éénhandsmengkraan                        |
| Thermostatische mengkraan                |

---

**Comment by MarcelVanDenBos** [comment]
Dank voor je suggestie. We gaan het wat minder letterlijk overnemen aangezien we anders redundantie creëren in ons model. We gaan een groot aantal waarden overnemen als installaties die je aan een ruimte kunt koppelen. 
Zo maken we onderscheid tussen een staand en hangend toilet. En afhankelijk van welke ruimte deze in zit bepaal je de punten. Idem voor Éénhandsmengkraan en Thermostatische mengkraan.
