### ISSUE TITLE
Referentiedata stelselgroepen mbt Woningwaarderingstelsel juli 2024

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#133]
In het nieuwe woningwaarderingsstelsel zijn sommige stelstelgroepen, of rubrieken zoals het beleidsboek deze nu noemt, anders genoemd, en ze hebben ook een andere implementatie. Het lijkt mij daarom goed om de referentiedata van de oude stelselgroepen te behouden ivm berekeningen met een peildatum voor 1 juli 2024 en nieuwe stelselgroepen toe te voegen voor berekeningen met een peildatum vanaf 1 juli 2024.

Nieuw toe te voegen stelselgroepen:
- `Verkoeling en verwarming` - voor 1 juli 2024 is dit `Verwarming`
- `Buitenruimten` - voor 1 juli 2024 is dit `Privé buitenruimten`
- `Gemeenschappelijke parkeerruimten` - voor 1 juli viel dit onder `Privé buitenruimten`
- `Prijsopslag monumenten en nieuwbouw` - voor 1 juli viel het deel mbt monumenten onder `Beschermd monument`

Dit zou dan alsvolgt geïmplementeerd kunnen worden:
```csv
WONINGWAARDERINGSTELSELGROEP;VKV;Verkoeling en verwarming;Waardering van verwarmde vertrekken, overige ruimten en verkeersruimten, inclusief extra punten voor verkoeling, op basis van NTA 8800 energielabels en vastgestelde eisen aan koelsystemen en verwarming.;1-7-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
WONINGWAARDERINGSTELSELGROEP;BUI;Buitenruimten;Waardering van privé- en gemeenschappelijke buitenruimten, met puntenaftrek voor woningen zonder buitenruimte.;1-7-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
WONINGWAARDERINGSTELSELGROEP;GPA;Gemeenschappelijke parkeerruimten;Waardering van parkeerplekken in een gemeenschappelijke ruimte die exclusief gebruikt worden door bewoners van minimaal twee adressen, met puntentoekenning afhankelijk van type en aanwezigheid van laadpaal.;1-7-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
WONINGWAARDERINGSTELSELGROEP;PMN;Prijsopslag monumenten en nieuwbouw;Prijsopslagen voor monumenten en nieuwbouw, waarbij extra percentages worden toegevoegd aan de maximale huurprijs voor rijks-, gemeentelijke of provinciaal aangewezen monumenten, evenals voor nieuwbouwwoningen die aan specifieke criteria voldoen.;1-7-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
```

**Comment by MarcelVanDenBos** [comment]
Dank voor je voorstel. We hebben dit opgenomen in de laatste versie.

**Comment by benverhees** [comment]
Super! Dank je wel!
