### ISSUE TITLE
verkeersruimte als ruimtesoort?

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#140]
Verkeersruimte bestaat niet als `ruimtesoort` in de referentiedata. In de Wet Betaalbare Huur is het belangrijk om te weten of een ruimte een verkeersruimte is (zie afbeelding). Zou de `ruimtesoort` van een `gang` en `hal` niet `verkeersruimte` moeten zijn i.p.v. `overige_ruimten`?

<img width="808" alt="image" src="https://github.com/user-attachments/assets/4f943592-1be6-4b04-8c06-94c7f1aca559">

**Comment by benataedes** [comment]
@sTomerG Verkeersruimte is als Ruimtesoort toegevoegd. Daarnaast hebben de ruimtedetailsoort Gang en Hal de ruimtesoort Verkeersruimte gekregen.

Dit zal vandaag als patch gepubliceerd worden.
