### ISSUE TITLE
referentiedata bevat `Ruimtedetailsoort` `gemeenschappelijk_dakterras` met code `GAK` en `GDA`

### ISSUE THREAD

**Issue by tiddoloos** [Aedes-datastandaarden/vera-referentiedata#144]
In de referentiedata is `Ruimtedetailsoort` `gemeenschappelijk_dakterras` te vinden met codes `GAK` en `GDA`. Dit was volgens mij een keer kort besproken in issue #108 . Uit die issue maak ik op dat `GDA` depricated is. Is het wellicht mogelijk om een einddatum op `GDA` te zetten of die hele record te verwijderen?

**Comment by benataedes** [comment]
Hoi @tiddoloos, we gaan een einddatum toekennen aan GDA. Zal binnenkort opgenomen in de referentiedata. Hiervoor is een nieuw pull request (#146) aangemaakt.
