### ISSUE TITLE
WONINGWAARDERINGSTELSELGROEP onzelfstandig

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#151]
In de vera-referentiedata zijn de `WONINGWAARDERINGSTELSELGROEP`en voor onzelfstandig nog van voor de Wet Betaalbare Huur van juli 2024.

De huidige stelselgroepen (rubrieken) voor onzelfstandig zijn zeer vergelijkbaar met zelfstandig (https://www.huurcommissie.nl/huurcommissie-helpt/beleidsboeken_html/waarderingsstelsel-onzelfstandige-woonruimte/de-rubrieken-van-het-woningwaarderingsstelsel-onzelfstandige-woonruimte#anker-3-rubriek-3-verkoeling-en-verwarming).

Alleen stelselgroepen 9, 12, en 13 zijn niet identiek. 

Dit levert mogelijk een uitdaging op, omdat dus eigenlijk alleen de `Parent` zou moeten veranderen van `WONINGWAARDERINGSTELSEL.ZEL` naar `WONINGWAARDERINGSTELSEL.ONZ`, maar dit levert uiteraard conflicten op ivm dupliceerde codes etc.

Wij zijn benieuwd naar jullie ideeën hierover!

**Comment by peterjan-aedesdatastandaarden** [comment]
We hebben nieuwe rubrieken toegevoegd. Daar waar rubrieken overlappen hebben we de parent weggehaald. Strikt genomen klopt dat niet omdat deze rubrieken niet voor de andere stelsels gelden. We gaan over een structurele oplossing nadenken. Vermoedelijk een constructie waarbij we een collectie van parents toestaan.
