### ISSUE TITLE
Definities PANDSOORT

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#154]
Ten eerste bedankt voor het toevoegen van de `PANDSOORT` :).

De definitie voor `Meergezinswoning` is niet helemaal correct, naar mijn idee. In een pand met één bedrijfsruimte en één zelfstandige woning zou de`PANDSOORT` voor die zelfstandige woning ook een `Meergezinswoning` moeten zijn. Het is dus niet vereist dat er _"meerdere zelfstandige wooneenheden, bedoeld voor bewoning van verschillende huishoudens, zijn ondergebracht"_.

Ook is het volgens mij zo, dat wanneer een onzelfstandige woning gelijk is aan het het hele pand, dit ook telt als een `Eengezinswoning`.

Volgens mij is de definite eigenlijk: 
- één verblijfsobject in een pand, met als functie wonen -> `Eengezinswoning`
- meerdere verblijfsobjecten in een pand waarvan minstens één met functie wonen  -> `Meergezinswoning`

Het woord _gezin_ is eigenlijk vrij misleidend of zelfs misplaatst voor de definitie dat het betreft, maar goed, zo beschouwt het CBS het en wij bij Woonstad Rotterdam gaan uit van hun autoriteit hierop.

Wellicht is het daarom goed om inspiratie op te doen vanuit hun definities:

https://www.cbs.nl/nl-nl/onze-diensten/methoden/begrippen/eengezinswoning
https://www.cbs.nl/nl-nl/onze-diensten/methoden/begrippen/meergezinswoning

```csv
PANDSOORT;EGW;Eengezinswoning;Een eengezinswoning is een zelfstandige woning die bedoeld is om door één huishouden bewoond te worden.;;;;Vastgoed
PANDSOORT;MGW;Meergezinswoning;Een meergezinswoning is een gebouw waarin meerdere zelfstandige wooneenheden, bedoeld voor bewoning door verschillende huishoudens, zijn ondergebracht.;;;;Vastgoed
```

**Comment by benataedes** [comment]
@sTomerG Bedankt voor je input. Voor de definitie van eengezinswoning en meergezinswoning hebben we gekeken naar het Besluit huurprijzen woonruimte (https://wetten.overheid.nl/BWBR0003237/2024-07-01). 

Hierin staat: 

- Eengezinswoning: een woning waarbij er geen andere woningen boven of onder de woning in kwestie bestaan. Hieronder vallen onder andere vrijstaande woningen, aaneen gebouwde woningen, zoals twee onder één kap gebouwde hele huizen en voorts rijtjeshuizen.

- Meergezinswoningen of duplexwoningen zijn alle woningen die geen eengezinswoning zijn.

De definitie zoals jij die noemt komt hier niet mee overeen. Ook de definitie van het cbs sluit m.i. hier ook niet bij aan.

Ik hoor graag hoe jij hiernaar kijken.

**Comment by sTomerG** [comment]
@benataedes na overleg binnen Woonstad zijn wij tot de conclusie gekomen dat wij de definitie zoals gehanteerd in de wet niet wenselijk vinden, en die van bijvoorbeeld het CBS wel. Wij gaan contact opnemen met de beleidsmakers om te vragen om de definitie te herzien. Ik kom hier op terug zodra ik meer informatie heb :)

**Comment by benataedes** [comment]
@sTomerG bedankt voor je reactie. Voor nu sluiten we het issue, indien nodig kun je een nieuw issue aanmaken.
