### ISSUE TITLE
Ruimtesoort Verkeersruimte heeft foutief domein

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#157]
Ruimtesoort Verkeersruimte heeft `vastgoed` als domein in plaats van `Vastgoed`:

https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/5882ac591bb103ef033139718395e5da8d4346bc/Referentiedata.csv#L1861

**Comment by FrancoisAtAedes** [comment]
Hi Ben, je hebt gelijk. We zullen het corrigeren.

**Comment by MarcelVanDenBos** [comment]
Aangepast in laatste build
