### ISSUE TITLE
Definities `Woningwaarderingstelselgroep`

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#165]
Bij de definities van
- `Bijzondere voorzieningen`
- `Bijzondere voorzieningen: zorgwoning en aanbelfunctie`
- `Bijzondere voorzieningen: zorgwoning`

```csv
WONINGWAARDERINGSTELSELGROEP;BIJ;Bijzondere voorzieningen;De groep criteria die betrekking heeft op de aanwezigheid van bijzondere voorzieningen, uitsluitend van toepassing bij zorgwoningen (Beleidsboek Waarderingsstelsel zelfstandige 
WONINGWAARDERINGSTELSELGROEP;BIA;Bijzondere voorzieningen: zorgwoning en aanbelfunctie;Waardering van bijzondere voorzieningen in een zorgwoning waaronder een aanbelfunctie met video- en audioverbinding;4-10-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
WONINGWAARDERINGSTELSELGROEP;BIZ;Bijzondere voorzieningen: zorgwoning;Waardering van bijzondere voorzieningen in een zorgwoning;4-10-2024;;WONINGWAARDERINGSTELSEL.ONZ;Vastgoed
```

staat dat het een zorgwoning betreft, maar de extra punten voor bijvoorbeeld een aanbelfunctie of laadpaal zijn niet specifiek voor zorgwoningen. Zie: https://www.huurcommissie.nl/huurcommissie-helpt/beleidsboeken_html/waarderingsstelsel-onzelfstandige-woonruimte/de-rubrieken-van-het-woningwaarderingsstelsel-onzelfstandige-woonruimte#anker-12-rubriek-12-bijzondere-voorzieningen-zorgwoning. Zorgwoning is een voorbeeld van een bijzondere voorziening. 

In alle eerlijkheid is dit ook vooral vreemd van het beleidsboek om de titel van het Rubriek _Bijzondere Voorzieningen: zorgwoning_ te noemen.

**Comment by peterjan-aedesdatastandaarden** [comment]
Hoi Tomer, inderdaad goed opgemerkt. Ik zal de omschrijving bij "Bijzondere voorzieningen: zorgwoning en aanbelfunctie" aanpassen in: "Waardering van de bijzondere voorzieningen: 'aanbelfunctie met video- en audioverbinding', laadpaal en het geheel aan voorzieningen die de woning tot zorgwoning maakt".
