### ISSUE TITLE
Rubriek `Prijsopslag Monumenten en Nieuwbouw`

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-referentiedata#166]
```csv
WONINGWAARDERINGSTELSELGROEP;PMN;Prijsopslag monumenten en nieuwbouw;Prijsopslagen voor monumenten en nieuwbouw, waarbij extra percentages worden toegevoegd aan de maximale huurprijs voor rijks-, gemeentelijke of provinciaal aangewezen monumenten, evenals voor nieuwbouwwoningen die aan specifieke criteria voldoen.;1-7-2024;;WONINGWAARDERINGSTELSEL.ZEL;Vastgoed
```

In de referentiedata bevindt zich de `WONINGWAARDERINGSTELSELGROEP` `Prijsopslag monumenten en nieuwbouw` voor zelfstandige woonruimten.

Voor onzelfstandig [is er geen opslag voor nieuwbouw](https://arc.net/l/quote/qipewiwg), dus is deze stelselgroep niet geschikt. Naar ons idee zijn er twee opties:

- voor onzelfstandig een stelselgroep aanmaken genaamd `Prijsopslag monumenten`
- stelselgroep `Prijsopslag monumenten en nieuwbouw` opsplitsen in `Prijsopslag monumenten` en `Prijsopslag nieuwbouw`

**Comment by peterjan-aedesdatastandaarden** [comment]
Beste Tomer,  bedankt! Omdat het paragraafkopje 'prijsopslag monumenten en nieuwbouw' ongewijzigd is voor zelfstandige woningen, lijkt het ons voor nu het beste om enkel de groep 'prijsopslag monumenten' toe te voegen waarbij de parent WONINGWAARDERINGSTELSEL.ONZ wordt.

**Comment by peterjan-aedesdatastandaarden** [comment]
Toegevoegd aan referentiedata
