### ISSUE TITLE
Vliering in Ruimtesoort en Ruimtedetailsoort

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-referentiedata#43]
Kan Vliering als Ruimtesoort toegevoegd in de referentiedata voor 3.1 en 3.2
Kan Vliering als Ruimtedetailsoort toegevoegd in de referentiedata voor 4.*

**Comment by MartijnVermeulenVERA** [comment]
Bedankt voor de feedback. Wij zetten je verzoek op onze backlog en komen er z.s.m. op terug.
