### ISSUE TITLE
Er mist een overeenkomstsoort Inschrijving. Kan die toegevoegd worden?

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-referentiedata#57]
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/a6bdcd4ca6f678125f0bbcf513a3d51fff9c2445/Referentiedata.csv#L1099C63-L1099C63

**Comment by MartijnVermeulenVERA** [comment]
Bedankt voor de opmerkzaamheid, deze overeenkomstsoort is toegevoegd
