### ISSUE TITLE
ADV dubbel gebruikt als INFORMATIEOBJECTDETAILSOORT

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-referentiedata#63]
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/9d52af8be4ea8c482dc3ca065fe97829a0c6817d/Referentiedata.csv#L806C1-L807C108

INFORMATIEOBJECTDETAILSOORT;ADV;Advies;;;;;Dossier;;
INFORMATIEOBJECTDETAILSOORT;ADV;Advertentietekst;Advertentietekst met (HTML) of zonder opmaak (Text).;;;;;;

De code ADV wordt dubbel gebruikt. Dat lijkt me niet de bedoeling toch?

**Comment by MartijnVermeulenVERA** [comment]
Opnieuw bedankt, dit was inderdaad fout. Het detailsoort 'ADV - Advertentietekst' was het laatst toegevoegd, deze is nu obsolete en vervangen door 'ADT - Advertentietekst'.
