### ISSUE TITLE
ISO 639-1 codering voor Taal?

### ISSUE THREAD

**Issue by EwoutAtAedes** [Aedes-datastandaarden/vera-referentiedata#80]
Het gebruik van drie letterige taal-codes is niet heel gebruikelijk (NLD, ENG, FRA, ..). Taalcodes met twee letters is meer in gebruik (NL, EN, FR, ...).  Voorstel om de twee letter-codering te gebruiken (ISO-639-1)

**Comment by MarcelVanDenBos** [comment]
Opgelost in 4.1.4

**Comment by MarcelVanDenBos** [comment]
dus
