### ISSUE TITLE
Informatiedomein voor RUIMTESOORT staat in foutieve kolom en mist voor sommige referentiedata

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#83]
Het informatiedomein voor `RUIMTESOORT` is in een verkeerde kolom geplaatst. Hierdoor mist het informatiedomein ook in de data die ontsloten wordt via de api. Ter illustratie heb ik als eerste regel een een correcte regel van `RUIMTEDETAILSOORT` toegevoegd.

Voor sommige regels in `AUTHENTIEKGEGEVENBRON`, `EENHEIDKLIMAATBEHEERSINGSOORT`,  en `WONINGWAARDERINGSTELSEL` mist het informatiedomein.

Daarnaast mist de laatste kolom een titel.

Soort | Code | Naam | Omschrijving | Begindatum | Einddatum | Parent | Informatiedomein |  | 
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
RUIMTEDETAILSOORT | ATR | Atrium / Patio | Niet overdekt atrium of patio | 24-4-2023 |  | RUIMTESOORT.BTR | Vastgoed |  | 
RUIMTESOORT | BTR | Buitenruimte | Een buitenruimte is een ruimte die volgens de woningwaardering als (privé) buitenruimte wordt gezien. Nader te specificeren met ruimtedetailsoort. | 24-4-2023 |  |  |  | Vastgoed | 
RUIMTESOORT | GEM | Gemeenschappelijke ruimten en voorzieningen | Een gemeenschappelijk ruimte of voorziening is een ruimte die volgens de woningwaardering als gemeenschappelijke ruimte of voorziening wordt gezien | 24-4-2023 |  |  |  |  | 
RUIMTESOORT | OVR | Overige ruimtes | Een ruimte die geen buitenruimte is, en die geen vertrek is volgens de definitie van de woningwaardering. Nader te specificeren met ruimtedetailsoort. | 24-4-2023 |  |  |  | Vastgoed | 
RUIMTESOORT | VTK | Vertrek | Een vertrek is een ruimte die volgens de woningwaardering als vertrek wordt gezien (Beleidsboek waarderingsstelsel zelfstandige woonruimte) | 24-4-2023 |  |  |  | Vastgoed | 
EENHEIDKLIMAATBEHEERSINGSOORT | IND | Individueel |  | 08-03-2024 |  |  |  |  | 
EENHEIDKLIMAATBEHEERSINGSOORT | COL | Collectief |  | 08-03-2024 |  |  |  |  | 
AUTHENTIEKGEGEVENBRON | BSN | BvBSN | Gegevens zijn gedeeld vanuit de basisvoorziening burgerservicenummer | 06-12-2023 |  |  |  |  | 
EENHEIDKLIMAATBEHEERSINGSOORT | IND | Individueel |  | 08-03-2024 |  |  |  |  | 
EENHEIDKLIMAATBEHEERSINGSOORT | COL | Collectief |  | 08-03-2024 |  |  |  |  | 
WONINGWAARDERINGSTELSEL | STA | Standplaatsen | Het puntensysteem binnen het woningwaarderingstelsel dat van toepassing is voor standplaatsen | 21-4-2023 |  |  |  |  | 
WONINGWAARDERINGSTELSEL | WOO | Woonwagens | Het puntensysteem binnen het woningwaarderingstelsel dat van toepassing is voor woonwagens | 21-4-2023 |  |  |  |  |

**Comment by EwoutAtAedes** [comment]
Issues in aantal kolommen opgelost. Tevens de verwijzing naar domein met uitzondering van AUTHENTIEKGEGEVENSOORT. Deze referentiedata.

**Comment by benverhees** [comment]
@EwoutAtAedes thanks voor de snelle fix! Komt deze update ook automatisch beschikbaar via de API?
