### ISSUE TITLE
CSV bevat non-breaking spaces

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#84]
De data in de csv bevat non-breaking spaces. Deze karakters kunnen problemen veroorzaken bij het verwerken en analyseren van de data. Zie onderstaande link met de zoekresultaten:

https://github.com/search?q=repo%3AAedes-datastandaarden%2Fvera-referentiedata%20%2F%5B%5Cxa0%5D%2F&type=code

**Comment by EwoutAtAedes** [comment]
non-breaking spaces zijn verwijderd

**Comment by benverhees** [comment]
@EwoutAtAedes thanks!
