### ISSUE TITLE
Foutieve omschrijving bij `CREDITEURSOORT.CLO` Crediteur leningen overheid

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#86]
De omschrijving bij `CREDITEURSOORT.CLO` lijkt niet te kloppen:

https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L371

**Comment by MarcelVanDenBos** [comment]
Goedemorgen Ben, Dank voor je input. Wij gaan dit vandaag met een patch oplossen. Met vriendelijke groet, VERA-architectuurteam
