### ISSUE TITLE
Omschrijvingen bij `AFSPRAAKVERZOEKSOORT` zijn verwisseld

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#87]
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L64-L65

**Comment by MarcelVanDenBos** [comment]
Goedemorgen Ben, Dank voor je input. Wij gaan dit vandaag met een patch oplossen. Met vriendelijke groet, VERA-architectuurteam
