### ISSUE TITLE
`RUIMTEDETAILSOORT.LOG` is twee keer gedefinieerd

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#88]
`RUIMTEDETAILSOORT.LOG` is twee keer gedefinieerd:
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L1724
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L1745

**Comment by MarcelVanDenBos** [comment]
Goedemorgen Ben, Dank voor je opmerking. We gaan dit vandaag met een patch oplossen. Met vriendelijke groet, VERA-architectuurteam
