### ISSUE TITLE
`RUIMTEDETAILSOORT.GTU` is twee keer gedefinieerd

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#89]
Er zijn twee definities voor `RUIMTEDETAILSOORT.GTU` met als parent `RUIMTESOORT.GEM`. Deze hebben als naam Gemeenschappelijke tuin en Gemeenschappelijk dakterras
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L1719-L1720
Mogelijk gerelateerd aan andere definitie met als naam`Gemeenschappelijk dakterras` en parent `RUIMTESOORT.BTR`
https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/475676fe7fc98ecc6d2a0d9a88fd239623692b8d/Referentiedata.csv#L1715

**Comment by MarcelVanDenBos** [comment]
Goedemorgen Ben, Dank voor je input. Wij gaan dit vandaag met een patch oplossen. Met vriendelijke groet, VERA-architectuurteam
