### ISSUE TITLE
Kast is niet beschikbaar als ruimtedetailsoort

### ISSUE THREAD

**Issue by WouterKol** [Aedes-datastandaarden/vera-referentiedata#91]
Kast ontbreekt nog als ruimte in Vera. Deze is nodig voor de Woning Waarderings berekening waarin de kast als ruimte meetelt (binnen bepaalde voorwaarden) als onderdeel van het vloeroppervlak.

In de Aedes ILS is Kast een ruimtetype.
Ruimte type is weer een attribuut van onder andere NVO (netto vloeroppervlak).

**Comment by RomyMans** [comment]
Hi Wouter, de ILS groep is bezig met een opschoning van de ruimtedetailsoort lijst tbv de volgende versie ILS 3.0. Na de opschoning zullen we ook voor harmonisatie met VERA zorgen. 
Bij de opschoning nemen we jouw punten mee: 

1. dit issue: inbouwkast toevoegen als ruimtetype in VERA (conform ILS)
2. issue #92 conflict "SCH" schuur vs schacht, 
3. issue #93 verkeersruimtes

**Comment by WouterKol** [comment]
Hi Romy,

Super, dank.
Wij blijven ze inschieten 😉.

Groeten aan de werkgroep!

Wouter


Wouter Kolbeek
Product Owner Integraties & Microservices
+31 6 50 22 85 13

Afdeling
Digitale Innovatie & Transformatie
Rochussenstraat 21
3015 EA Rotterdam

www.woonstadrotterdam.nl<http://www.woonstadrotterdam.nl/>

***@***.***



Van: Romy Mans ***@***.***>
Verzonden: vrijdag 10 mei 2024 11:40
Aan: Aedes-datastandaarden/vera-referentiedata ***@***.***>
CC: Wouter Kolbeek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Aedes-datastandaarden/vera-referentiedata] Kast is niet beschikbaar als ruimtedetailsoort (Issue #91)


Hi Wouter, de ILS groep is bezig met een opschoning van de ruimtedetailsoort lijst tbv de volgende versie ILS 3.0. Na de opschoning zullen we ook voor harmonisatie met VERA zorgen.
Bij de opschoning nemen we jouw punten mee:

  1.  dit issue: inbouwkast toevoegen als ruimtetype in VERA (conform ILS)
  2.  issue #92<https://github.com/Aedes-datastandaarden/vera-referentiedata/issues/92> conflict "SCH" schuur vs schacht,
  3.  issue #93<https://github.com/Aedes-datastandaarden/vera-referentiedata/issues/93> verkeersruimtes

**Comment by MarcelVanDenBos** [comment]
Besproken in VERA-AT. Onderscheid is nodig tussen:
- Inpandige berging:  Een ruimte binnen de woning die wordt gebruikt voor het opslaan van goederen, gereedschappen, fietsen, of andere items, vaak voorzien van planken, rekken of kasten voor organisatie.
- Externe berging: Een ruimte binnen het gebouw, maar buiten de woning, die wordt gebruikt voor het opslaan van goederen, gereedschappen, fietsen, of andere items, vaak voorzien van planken, rekken of kasten voor organisatie.
- buiten berging: Een afzonderlijke structuur buiten een gebouw, zoals een tuinhuisje, schuur of garage, die wordt gebruikt voor het opslaan van tuinapparatuur, gereedschappen, of seizoensgebonden items.

**Comment by EwoutAtAedes** [comment]
Comment van Marcel (2 augustus) hoort bij issue #92 en zal daar verder behandeld wordeen

**Comment by RomyMans** [comment]
Met de oplevering van de ILS-woco 3.0 vindt verdere harmonisatie met VERA plaats. In die versie van de ILS-woco staat kast als ruimtetype, en dus zal dan ook aan bod komen hoe dit ruimtetype in VERA zal landen.
