### ISSUE TITLE
Moederhaard bij EENHEIDKLIMAATBEHEERSING

### ISSUE THREAD

**Issue by bastiaanrodenburg** [Aedes-datastandaarden/vera-referentiedata#94]
Een moederhaard is een gaskachel in de woonkamer waarbij de warmte via leidingen ook verspreid wordt naar andere ruimtes. Zou toegevoegd kunnen worden aan EENHEIDKLIMAATBEHEERSING. Net zoals vloerverwarming er al in staat. Dat is ook een distributiesysteem bij een CV-ketel of warmtepomp. Dus bij een moederhaardsysteem zou je twee regels krijgen: GAS en MHD. Bij een vloerverwarmingssysteem heb je ook twee regels. Bijvoorbeeld WAC en VLV. 
Er kan ook gekozen worden om Moederhaard te definiëren als het complete systeem, dus de kachel en de distributie naar andere ruimtes. Dat heeft wel mijn voorkeur maar zou niet in lijn zijn met het feit dat vloerverwarming ook als losse regel in EENHEIDKLIMAATBEHEERSING staat.

**Comment by EwoutAtAedes** [comment]
Beste Bastiaan,
bedankt voor jouw voorstel. We gaan mee in jouw voorstel om 1 nieuwe regel toe te voegen voor het volledige systeem van de moederhaard (de centrale gaskachel) inclusief distributie naar de andere ruimtes. Code wordt dan MOE (Moederhaard)
