### ISSUE TITLE
Foutieve parent voor eenheidklimaatbeheersing Openhaard

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-referentiedata#98]
Openhaard is gedefinieerd met `EENHEIDKLIMAATBEHEERSINGSOORT.COL` als parent, terwijl ik zou verwachten dat dit `EENHEIDKLIMAATBEHEERSINGSOORT.IND` moet zijn.

https://github.com/Aedes-datastandaarden/vera-referentiedata/blob/a2323e64fb52d936f3aa7fdadcee247d6b66f4d1/Referentiedata.csv#L685

**Comment by EwoutAtAedes** [comment]
Beste Ben, bedankt voor de melding. Dit is inderdaad een individuele klimaatbeheersing. We passen dit aan in de volgende versie van de referentiedata
